FROM rabbitmq:latest

LABEL maintainer="Lin Bake<wowlc0203@qq.com>"

RUN rabbitmq-plugins enable rabbitmq_management

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       wget \
    && rm -rf /var/lib/apt/lists/*
RUN wget https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb \
    && sudo dpkg -i packages-microsoft-prod.deb

# Install .NET Core
RUN sudo apt-get update; \
  sudo apt-get install -y apt-transport-https && \
  sudo apt-get update && \
  sudo apt-get install -y dotnet-sdk-5.0
