version: "3.8"

services:
  scm:
    image: gitlab/gitlab-ce
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url='http://172.18.0.2/'
        gitlab_rails['time_zone'] = 'Asia/Shanghai'
        gitlab_rails['initial_root_password'] = 'P@ssw0rd'
        gitlab_rails['initial_shared_runners_registration_token'] = 'qGKy2y7SbJosh4mmHsgL'
    container_name: gitlab
    hostname: 'scm'
    restart: always
    networks:
      containernet:
        ipv4_address: 172.18.0.2
    volumes: 
      - /home/gitlab/config:/etc/gitlab
      - /home/gitlab/logs:/var/log/gitlab
      - /home/gitlab/data:/var/opt/gitlab
    ports:
      - "8080:80"
      - "8443:443"
      - "222:22"
  database:
    image: mysql
    container_name: database
    hostname: 'database'
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=P@ssw0rd
      - MYSQL_USER=bake
      - MYSQL_PASSWORD=P@ssw0rd
    networks:
      containernet:
        ipv4_address: 172.18.0.3
  deployment:
    image: wowlc0203/rabbitmq
    container_name: runtime
    restart: always
    hostname: 'runtime'
    ports:
      - 15672:15672
    networks:
      containernet:
        ipv4_address: 172.18.0.4
  scm-runner:
    image: wowlc0203/gitlab-runner
    container_name: runner
    hostname: 'runner'
    restart: always
    #entrypoint: gitlab-runner register --config /tmp/runner-config.toml --non-interactive --url "http://172.18.0.2/" --registration-token "qGKy2y7SbJosh4mmHsgL" --name "a baisc shell runner" --tag-list "shell,test" --locked="false" --executor "shell" --run-untagged="true" --access-level="not_protected"
    #command: gitlab-runner register --config /tmp/runner-config.toml --non-interactive --url "http://172.18.0.2/" --registration-token "qGKy2y7SbJosh4mmHsgL" --name "a baisc shell runner" --tag-list "shell,test" --locked="false" --executor "shell" --run-untagged="true" --access-level="not_protected"
    #environment:
    #  - CI_SERVER_URL='http://172.18.0.2/'
    #  - CI_JOB_TOKEN='qGKy2y7SbJosh4mmHsgL'
    #  - CI_RUNNER_DESCRIPTION='gitlab job runner'
    #  - CI_RUNNER_TAGS='test'
    networks:
      containernet:
        ipv4_address: 172.18.0.5
    volumes: 
      - /srv/gitlab-runner/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
  nuget:
    image: didstopia/nuget-klondike
    container_name: nuget
    hostname: 'nuget'
    restart: always
    command: htpasswd -b -c /data/klondike_users bake P@ssw0rd
    ports:
      - "9000:8080"
    networks:
      containernet:
        ipv4_address: 172.18.0.6
  #databaseadmin:
  #  image: adminer
  #  container_name: adminer
  #  hostname: 'adminer'
  #  restart: always
  #  ports:
  #    - "8888:8080"
  #  networks:
  #    containernet:
  #      ipv4_address: 172.18.0.7
networks:
  containernet:
    name: containernet
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.18.0.0/24"
          gateway: "172.18.0.200"
volumes:
  git-data:
