FROM gitlab/gitlab-runner:latest

LABEL maintainer="Lin Bake<wowlc0203@qq.com>"

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
		sudo \
        curl \
        git \
        wget \
    && rm -rf /var/lib/apt/lists/*
	
RUN wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
	&& sudo dpkg -i packages-microsoft-prod.deb

# Install .NET SDK
RUN sudo apt-get update; \
	sudo apt-get install -y apt-transport-https && \
	sudo apt-get update && \
	sudo apt-get install -y dotnet-sdk-5.0
    && dotnet help

# Install PowerShell global tool
RUN powershell_version=7.2.0-preview.1 \
    && curl -SL --output PowerShell.Linux.x64.$powershell_version.nupkg https://pwshtool.blob.core.windows.net/tool/$powershell_version/PowerShell.Linux.x64.$powershell_version.nupkg \
    && powershell_sha512='4017c159197bb6fe901f8261dd4f23ea9aaf583d7f028478f2f303f6b0ac86e2782fa8646f327047954487a57de8e4b8d46e5bff8a1c0e26536a0da847fa721d' \
    && echo "$powershell_sha512  PowerShell.Linux.x64.$powershell_version.nupkg" | sha512sum -c - \
    && mkdir -p /usr/share/powershell \
    && dotnet tool install --add-source / --tool-path /usr/share/powershell --version $powershell_version PowerShell.Linux.x64 \
    && dotnet nuget locals all --clear \
    && rm PowerShell.Linux.x64.$powershell_version.nupkg \
    && ln -s /usr/share/powershell/pwsh /usr/bin/pwsh \
    && chmod 755 /usr/share/powershell/pwsh \
    # To reduce image size, remove the copy nupkg that nuget keeps.
    && find /usr/share/powershell -print | grep -i '.*[.]nupkg$' | xargs rm
